### ISSUE TITLE
Obter os tempos de execução diretamente do redis

### ISSUE THREAD

**Issue by PabloAlexandre** [Kenoby-Labs/monwatch#4]
Hoje, para calcular o tempo atual, utilizamos a lib `dayjs`. O problema é que como ela depende de cada tempo, de cada servidor, caso a lib use mais de um servidor, estamos gerando um ponto de falha por inconsistência. Para resolver isso, precisamos alterar todas as obtenções de tempo e começar a usar a função `TIME` do redis. Assim podemos centralizar o horário e lidar melhor com vários clusters, permitindo escalar

**Comment by thiagozampieri** [comment]
Vou pegar essa
